name: "Zunder Lab @ UVa"
description: "This is the official web page for the Eli Zunder Lab at UVa."

url: "http://zunderlab.com"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
